export const SET_POKEMONS_BASIC_INFO = "SET_POKEMONS_BASIC_INFO";
export const SET_POKEMON = "SET_POKEMON";
export const SET_POSSIBLE_TYPES = "SET_POSSIBLE_TYPES";
export const SET_FILTER = "SET_FILTER";
